configured_endpoints: 11
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/bluehive-health--llc-dash%2Fbluehive-2e0dd34abf24f9ccaf6748bf25a3d7555e78b6c4700ea0760fc569acead0eea7.yml
openapi_spec_hash: acc719f39e93331e054a775c4e94d2ac
config_hash: d941d39df55a7c6dbf709cbe6fbbf4a0
