configured_endpoints: 11
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/bluehive-health--llc-dash%2Fbluehive-ee1fc8e6f62efcb57f28c62d90668dd4f1403689ac435e8c17cb67bdb2d65544.yml
openapi_spec_hash: dfd681db0c339c66ca00d98b20a3731b
config_hash: d941d39df55a7c6dbf709cbe6fbbf4a0
