configured_endpoints: 7
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/bluehive-health--llc-dash%2Fbluehive-c0bee41c493650cd9cc5f1e75cc4e55b0e4b29cf6fba907710df8cbce4fc52f8.yml
openapi_spec_hash: 720a7d4468e6cd4ff95351326e518ac4
config_hash: 4dbc0fb38d6fe1b37e36c8819098ff6b
